use Pistons
go

DROP TRIGGER AjoutPiece
DROP TRIGGER TriggerCumul
go

DROP FUNCTION fn_CategoriserPiece
go

DROP PROCEDURE Ajouter_machine
DROP PROCEDURE CreerCumul
DROP PROCEDURE LancerLot
DROP PROCEDURE SortieStock
DROP PROCEDURE EntreeStock
DROP PROCEDURE DemarrerLot
DROP PROCEDURE Categorisation
DROP PROCEDURE Liberer_presse
DROP PROCEDURE ArretLot
go

DROP VIEW VueStocksCategorie
DROP VIEW VueRuptureStock
DROP VIEW VueEtatPresse
go

DROP USER ederson
DROP USER walker
DROP USER kompany
DROP USER otamendi 
DROP USER danilo 
DROP USER debruyne 
DROP USER gundogan 
DROP USER dsilva 
DROP USER bsilva 
DROP USER sane 
DROP USER sterling 
DROP USER aguero 
DROP USER guardiola
go

DROP LOGIN resp_appli
DROP LOGIN resp_atelier1
DROP LOGIN resp_atelier2
DROP LOGIN resp_production1
DROP LOGIN resp_production2
DROP LOGIN controleur1 
DROP LOGIN controleur2
DROP LOGIN controleur3
DROP LOGIN magasinier1
DROP LOGIN magasinier2
DROP LOGIN magasinier3
DROP LOGIN resp_qualité1
DROP LOGIN resp_qualité2
go

DROP ROLE CONTROLEUR
DROP ROLE RESP_ATELIER
DROP ROLE RESP_PRODUCTION
DROP ROLE RESP_QUALITE
DROP ROLE RESP_APPLI
DROP ROLE MAGASINIER
go

DROP TABLE CUMUL

DROP TABLE PIECE
go

DROP TABLE STOCK

DROP TABLE LOT
go

DROP TABLE ETAT_LOT
go

DROP TABLE MODELE

DROP TABLE CATEGORIE

DROP TABLE MACHINE
go

DROP TYPE TypeDiametre

DROP TYPE TypeCategorie

DROP TYPE TypeModele

DROP TYPE TypePieceLot
go

